version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      #step 1: obtain repo from GitHub
      - checkout
      #step 2: run the dependecies, to install 
      - run:
          name: Install dependencies          
          command: pip install -e requirements.txt
      - run:
          name: run tests
          command:
            flake8 --exclude=env* --statistics
            pytest -v